# Generated by Django 4.0.6 on 2022-07-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_current_round_delete_accesstokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='questions/'),
        ),
    ]
