# Generated by Django 4.0.6 on 2022-08-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_clues_clue_no_clues_wait_time_in_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=10),
        ),
    ]
