# Generated by Django 4.0.6 on 2022-08-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_question_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_clue',
        ),
        migrations.AddField(
            model_name='question',
            name='clue',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='clue_wait_time',
            field=models.IntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='Clues',
        ),
    ]
