# Generated by Django 4.0.6 on 2022-12-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_current_clue_question_clue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.URLField(default=None, null=True, verbose_name='Avatar of the user: '),
        ),
    ]
