# Generated by Django 4.1.4 on 2023-01-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reverberate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=20)),
                ('roll_no', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
            ],
        ),
    ]
