# Generated by Django 4.1.4 on 2023-01-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_debreverberate'),
    ]

    operations = [
        migrations.AddField(
            model_name='debreverberate',
            name='teamname',
            field=models.CharField(default='', max_length=10),
        ),
    ]
