# Generated by Django 4.1.4 on 2023-01-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_debreverberate_teamname'),
    ]

    operations = [
        migrations.AddField(
            model_name='debreverberate',
            name='hallno',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='reverberate',
            name='hallno',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
